### ISSUE TITLE
Chansey's HA isn't italics

### ISSUE THREAD

**Issue by operislaborat** [richi3f/pokemon-trading-spreadsheet#5]
![screen shot 2017-01-15 at 8 29 17 am](https://cloud.githubusercontent.com/assets/21980911/21957520/c8e988be-dafc-11e6-93bf-142eb4c1390d.png)

This bug resulted from the row not having the dex number, the dex number didn't automatically fill in(is the google app script on a timer; how long is it?).

**Comment by richi3f-zz** [comment]
Hello there! The Google Document does not have any script. It is a plain simple formula: `=if(isblank(B2), , match(B2,DB!$A$2:$A$803,0))`. You can copy/drag it from another cell and that should fix the HA problem.

**Comment by GiacomoLaw** [comment]
I'm getting the same problem with Tepig:

https://gyazo.com/86608c07a858d87db5dc539095432288

I tried doing what you said, but it isn't working 😕
