### ISSUE TITLE
OT showing?

### ISSUE THREAD

**Issue by GiacomoLaw** [richi3f/pokemon-trading-spreadsheet#6]
Thanks for the awesome tool!

An OT column is showing on my page even though it's not on the sheet:

https://giacomolaw.github.io/pokemon/#2

Here is the sheet:

https://docs.google.com/spreadsheets/d/1XPa5pC3Y8ybTfIjiQR605FfohxtvLEYAY4_-POVgi1s/pubhtml

I also added a levels column and it's not showing 😕 

Thank you!

**Comment by richi3f-zz** [comment]
Hi there! This is caused by the Lv. and EV columns. If the script detects one of those columns, it assumes that you are listing valuable Pokémon instead of breedables. That is why it is expecting to find OT/TID. You can look into line 605 of `script.js` to modify this behavior.

**Comment by GiacomoLaw** [comment]
Okay, thank you very much.

**Comment by GiacomoLaw** [comment]
@richi3f Also, is there a way I can add a note to the site? 😄

**Comment by GiacomoLaw** [comment]
@richi3f Just a few questions about breeding if it's okay. Thanks so much for the awesome work!

1. When I list the IVs for a Pokemon, they sometimes change even if I breed the same Pokemon twice. For example, the IVs for Eevee A are completely different to the IVs for Eevee B, even though I've breeded Eevee C with the same Ditto. What should I put down for their IVs?
2. What should I put down as the nature as it changes?
3. Am I correct in believing Breedables are Pokemon you breed to get the end result? I mean if Bob goes onto my sheet and asks for Eevee, I dump Eevee into the nursery, breed it with Ditto, hatch the egg and trade it to Bob. Am I correct in thinking this?

Thanks so much!

**Comment by miracleceleste** [comment]
Sounds like you need to do a bit more research on breeding mechanics. Even when breeding the same 2 perfect Pokémon, there's only a 1/32 chance that two babies will have the same IVs. When people put Pokémon under their "breedables" tab, they either put no IVs or the optimal spread. They're saying they currently have the correct parents to breed the requested Pokémon (though it may take a few tries to get the correct IV spread. 

For example, I have a Jolly Mimikyu with 31,31,31,xx,31,31 and 4 egg moves in my tab 

That means when someone requests a Mimikyu, I'll pull out my 6IV parent and my 6IV ditto , attach the necessary everstone and destiny knot and start breeding until I get the right Mimikyu (1 in 6 chance either the given parents). 

That's how the breedables tab works. (Or as is understood by the greater community)

2) having one of the parents hold an everstone guarantees the baby will have the same nature

**Comment by GiacomoLaw** [comment]
Thank you!
